### ISSUE TITLE
Can you provide an example using spring boot?

### ISSUE THREAD

**Issue by kespinosa05** [ayltai/spring-graalvm-native-plugin#1]
**Describe the bug**
Please provide an example using spring boot.
I tried to apply this plugin but when I run gradle buildNativeImage, the task never finish.

**To Reproduce**
1. Create a spring boot project with gradle
2. apply plugin 

```groovy
apply plugin: 'com.github.ayltai.spring-graalvm-native-plugin'
nativeImage {
    mainClassName = 'ec.com.smx.base.BaseSpringBootApplication'

    traceClassInitialization    = true
    traceClassInitialization    = false
    removeSaturatedTypeFlows    = false
    reportExceptionStackTraces  = true
    printAnalysisCallTree       = false
    enabledAllSecurityServices  = false
    staticallyLinked            = false
    warnMissingSelectorHints    = false
    removeUnusedAutoConfig      = true
    verbose                     = false
    springNativeVerbose         = false
    removeYamlSupport           = true
    removeXmlSupport            = true
    removeSpelSupport           = true
    removeJmxSupport            = true
    maxHeapSize                 = '6G'
    verify                      = false
    //springNativeMode            = 'feature'  //agent|feature|functional
    //dumpConfig                  = '/tmp/dump.txt' // dumps the configuration to the specified file.
    //initializeAtBuildTime       = //Unsupported options
}
```
3. add dependencies
    compile 'org.springframework.experimental:spring-graalvm-native:0.7.1'
    annotationProcessor 'org.springframework.experimental:spring-graalvm-native:0.7.1'
    compileOnly 'org.springframework:spring-context-indexer'
    annotationProcessor 'org.springframework:spring-context-indexer'
4. Run task 'gradle buildNativeImage'

**Expected behavior**
Task completed

**Screenshots**
![image](https://user-images.githubusercontent.com/15805567/85780309-15a5a080-b6ea-11ea-861e-6b67100e17a8.png)

**Desktop (please complete the following information):**
 - OS:  macOS
 - Version: 10.15.5

**Comment by ayltai** [comment]
Thanks for the feedback. Yes, I'm going to create a sample project and add more instructions on how to use this based on the sample project.
I'm not sure what caused the issue, and it's probably not related, but we don't need to add any extra dependencies (spring-graalvm-native or spring-context-indexer). This plugin handles it for you.
What are the computer configurations used for this build? CPU and RAM?

**Comment by ayltai** [comment]
Please refer to this sample project:
https://github.com/ayltai/spring-graalvm-native-plugin/blob/master/samples/springmvc-tomcat/build.gradle
