### ISSUE TITLE
Why do you choose Spring Native for your app

### ISSUE THREAD

**Issue by HelloTo4x** [ayltai/spring-graalvm-native-plugin#149]
Hi, i am reading your project, but i have a question, why do u choose Spring Native for your app instead of Quarkus of other framework for build with GraalVM. Can u tell me the pros and cons of Spring Native ? When should we use it instead of other framewoks ?

**Comment by ayltai** [comment]
This is a Gradle plugin which is meant to be used with an application project. Some projects need/want it, some don't, depending on the application projects who use this plugin. Having said that, it is the application project author who considers the pros/cons of using this plugin/Spring Native, not the plugin itself to consider the pros/cons. For example, it doesn't make sense to ask the pros and cons of a gun (a tool, a plugin, etc). It is who/when/where/how to use it that matters.
