### ISSUE TITLE
Graal 20.3: rework non-Boolean setting "traceClassInitialization"

### ISSUE THREAD

**Issue by mmoayyed** [ayltai/spring-graalvm-native-plugin#30]
**Is your feature request related to a problem? Please describe.**

Using `traceClassInitialization = true` in the plugin configuration, when building against GraalVM 20.3 presents the following:

```
Error: Non-boolean option 'TraceClassInitialization' can not use +/- prefix. Use 'TraceClassInitialization=<value>' format
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Describe the solution you'd like**

Support the `TraceClassInitialization` setting to allow for the new accepted formats and values for GraalVM 23.0.

**Describe alternatives you've considered**

Remove `traceClassInitialization = true`.

**Additional context**

Seems like this line should be reworked when using 23.0:

```
SpringGraalNativeTask.appendCommandLineArg(args, "-H:+TraceClassInitialization", this.traceClassInitialization);
```

This should be removed or changed to the new format of the option when running with Graalvm 20.3+.
The new format is:

> Comma-separated list of fully qualified class names that class initialization is traced for.

Happy to send a pull request if necessary.

**Comment by ayltai** [comment]
Thanks for reporting. A new version 1.3.0 is released. `traceClassInitialization` is now deprecated. Use `traceClassInitializationEnabled` for GraalVM 20.2.0 or below, and pass a list of class name strings to `traceClassInitializationFor` for GraalVM 20.3.0.
