### ISSUE TITLE
Wrong property for removing xml support

### ISSUE THREAD

**Issue by woglinde** [ayltai/spring-graalvm-native-plugin#39]
Hi,

according to the code 
https://github.com/spring-projects-experimental/spring-graalvm-native/blob/e41b5dbdd4ac39c3d7a823a988931e57ece94736/spring-graalvm-native-feature/src/main/java/org/springframework/nativex/support/ConfigOptions.java#L141
of spring-native the flag to remove xml support is spring.xml.ignore instead of spring.native.remove-xml-support.

**Comment by ayltai** [comment]
Thanks for pointing that out. It seems it is incorrect for both XML and SpEL. I'll correct that in the next release.

**Comment by ayltai** [comment]
Fixed in release 1.4.1
