### ISSUE TITLE
Caused by: jdk.vm.ci.common.JVMCIError: failed guarantee: DynamicNewInstanceNode.instanceType is constant, should have been canonicalized to NewInstanceNode.

### ISSUE THREAD

**Issue by oryjk** [ayltai/spring-graalvm-native-plugin#6]
**Describe the bug**
when I use `gradle buildNativeImage`, an error occur 

`Caused by: jdk.vm.ci.common.JVMCIError: failed guarantee: DynamicNewInstanceNode.instanceType is constant, should have been canonicalized to NewInstanceNode.`

**To Reproduce**
my gradle file
```
apply plugin: 'org.springframework.boot'
apply plugin: 'com.github.ayltai.spring-graalvm-native-plugin'
dependeny…………

nativeImage {
    mainClassName              = 'com.xxx.config.ConfigServer'
    traceClassInitialization   = true
    reportExceptionStackTraces = true
    removeUnusedAutoConfig     = true
    removeYamlSupport          = true
    removeSpelSupport          = true
    removeJmxSupport           = true
    maxHeapSize                = '4G'
}
```

graalvm version: graalvm-ce-java8-20.1.0
spring-graalvm-native-plugin version: 1.0.7

**Screenshots**
![image](https://user-images.githubusercontent.com/6252789/88882597-e7752c80-d264-11ea-8b4b-21df4eca7423.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.3

**Comment by ayltai** [comment]
From the stacktrace, that was an error caused by GraalVM, not related to this plugin.
