### ISSUE TITLE
set enableHttps use enableHttp variable

### ISSUE THREAD

**Issue by likevin904** [ayltai/spring-graalvm-native-plugin#74]
In  SpringGraalNativeExtension, set enableHttps used enableHttp variable

   public void setEnableHttps(final boolean enableHttps) {
        this.enableHttps.set(enableHttp);
    }

**Comment by ayltai** [comment]
Fixed in https://github.com/ayltai/spring-graalvm-native-plugin/releases/tag/release%2F1.4.3
