### ISSUE TITLE
gu.exe NotExist on Windows

### ISSUE THREAD

**Issue by vicasong** [ayltai/spring-graalvm-native-plugin#82]
Running the plugin throws an exception:
         Cannot run program "C:\Users\<userName>\IdeaProjects\com\demo\build\tmp\buildNativeImage\graalvm-ce-java8-21.0.0\bin\gu.exe":  CreateProcess error=2, The system cannot find the file specified

 - OS: Windows10
 - Plugin Version: 1.4.5

And I only found `du.cmd`  file in this directory.

**Comment by ayltai** [comment]
There should be `gu.cmd` in `graalvm-ce-java8-21.0.0\bin\`. Release 1.4.6 fixed this accordingly.
