### ISSUE TITLE
version `1.4.9`  not published to plugins.gradle.org/m2

### ISSUE THREAD

**Issue by scottmf** [ayltai/spring-graalvm-native-plugin#87]
hi @ayltai , i don't see version `1.4.9` published to plugins.gradle.org/m2.  Is there a lag or is there another issue?

https://plugins.gradle.org/m2/com/github/ayltai/spring-graalvm-native-plugin/com.github.ayltai.spring-graalvm-native-plugin.gradle.plugin/

**Comment by ayltai** [comment]
Both v1.4.8 and v1.4.9 are pending approval from the Gradle plugin website.

**Comment by ayltai** [comment]
It is approved
