### ISSUE TITLE
Support "-H:-CheckToolchain" (or other command-line options)

### ISSUE THREAD

**Issue by mmoayyed** [ayltai/spring-graalvm-native-plugin#9]
**Is your feature request related to a problem? Please describe.**

Attempting to build a native image presents the following error:

```
Feature operating in FEATURE mode
Removing unused configurations
Removing Yaml support
Use -Dspring.native.verbose=true on native-image call to see more detailed information from the feature
[cas:7157]        setup:     790.40 ms,  0.96 GB
Error: Collecting native-compiler info with '/usr/bin/cc -v ' failed
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
com.oracle.svm.core.util.UserError$UserException: Collecting native-compiler info with '/usr/bin/cc -v ' failed
To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
```

At the moment, `-H:-CheckToolchain` is not supported. 

**Describe the solution you'd like**

Support a configuration flag for `-H:-CheckToolchain`, or support a general configuration where command-line options can be specified in the plugin config. 

**Additional context**

- Gradle 6.6.1
- Plugin 1.2.1
- Spring Boot 2.3.3
- GraalVM EE 20.2.0 (build 11.0.8.0.2+1-LTS-jvmci-20.2-b03)

If you'd like, I can certainly put together a pull request with some guidance.

**Comment by ayltai** [comment]
It seems you are missing a C compiler /usr/bin/cc which GraalVM needs. If you add CheckToolchain flag, it will not run /usr/bin/cc -v but it will fail at a later step because your machine is missing some necessary files.

**Comment by mmoayyed** [comment]
Thank you for the tip. 

I am running MacOS Catalina 10.15.6, and based on the [docs](https://www.graalvm.org/reference-manual/native-image/#prerequisites), when I run: `xcode-select --install`, I get back `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`. There are no other updates. 

Also,

```
/usr/bin/cc -v                                                                                                              ─╯
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Do I need something else installed?

**Comment by ayltai** [comment]
Please try version 1.2.2 with this configuration:
```groovy
nativeImage {
    mainClassName = '...'
    disableToolchainChecking = true
    ...
}
```

**Comment by mmoayyed** [comment]
Thank you.
